name: Validate for PR
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  validate:
    name: Validate abbreviate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.21'
      - run: make ci-test deps build acceptance-test
        env:
          GO111MODULE: on
